//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementApp.SalesManagementDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInvoiceDetail
    {
        public int InvoiceDetailID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SalesInvoice SalesInvoice { get; set; }
    }
}
